### ISSUE TITLE
Wheres the walk sim

### ISSUE THREAD

**Issue by Tavrie** [GiraffeasGorilla/MyDimenions#3]

**Comment by iwantapenguinn** [comment]
he gave up or copyright

**Comment by Tavrie** [comment]
> he gave up or copyright

NOOOOOOOOOOOO

**Comment by GiraffeasGorilla** [comment]
> he gave up or copyright

copyright. ok so the thing is I DID NOT MAKE WALKSIM. STOP ASKING

**Comment by Tavrie** [comment]
WHAT WHUY

**Comment by GiraffeasGorilla** [comment]
> WHAT WHUY

well the actual owner of walk sim just stopped updating it so i started updating it and publishing the updates until the owner messaged me and said to stop

**Comment by Tavrie** [comment]
> > WHAT WHUY
> 
> well the actual owner of walk sim just stopped updating it so i started updating it and publishing the updates until the owner messaged me and said to stop

why tho? like if he stopped updating u shouldnt listen to him since he doesnt wanna update it anymore? like thats bs or maybe im wrong?

**Comment by Tavrie** [comment]
maybe i will remake it

**Comment by Tavrie** [comment]
maybe not

**Comment by Tavrie** [comment]
but is it that hard.?

**Comment by GiraffeasGorilla** [comment]
> but is it that hard.?

yes very

**Comment by GiraffeasGorilla** [comment]
> > > WHAT WHUY
> > 
> > 
> > well the actual owner of walk sim just stopped updating it so i started updating it and publishing the updates until the owner messaged me and said to stop
> 
> why tho? like if he stopped updating u shouldnt listen to him since he doesnt wanna update it anymore? like thats bs or maybe im wrong?

well its because its copyrighted. i can go to jail if i don't stop

**Comment by Tavrie** [comment]
If i do get to jail idgaf

**Comment by Tavrie** [comment]
> > > > WHAT WHUY
> > > 
> > > 
> > > well the actual owner of walk sim just stopped updating it so i started updating it and publishing the updates until the owner messaged me and said to stop
> > 
> > 
> > why tho? like if he stopped updating u shouldnt listen to him since he doesnt wanna update it anymore? like thats bs or maybe im wrong?
> 
> well its because its copyrighted. i can go to jail if i don't stop

im doing it for you

**Comment by Tavrie** [comment]
BUT TRUST I WILL DO IT

**Comment by GiraffeasGorilla** [comment]
> If i do get to jail idgaf

yes

**Comment by GiraffeasGorilla** [comment]
> BUT TRUST I WILL DO IT

you will get copyrighted dont do it

**Comment by Tavrie** [comment]
> > BUT TRUST I WILL DO IT
> 
> 
> 
> you will get copyrighted dont do it

I'm gonna do it for you

**Comment by GiraffeasGorilla** [comment]
> > > BUT TRUST I WILL DO IT
> > 
> > 
> > you will get copyrighted dont do it
> 
> I'm gonna do it for you

DONT DO IT.

**Comment by Tavrie** [comment]
> > > > BUT TRUST I WILL DO IT
> 
> > > 
> 
> > > 
> 
> > > you will get copyrighted dont do it
> 
> > 
> 
> > I'm gonna do it for you
> 
> 
> 
> DONT DO IT.

Okay fine

**Comment by Tavrie** [comment]
man freak it I'm doing this for you freak your friend that told you to stop updating it I'm gonna remake it trust me if I go to jail I do not care and I'm 14 IM DOING THIS FOR YOU

**Comment by Tavrie** [comment]
and if u want to join me ask me... but if you don't that's fine I don't want u go to jail over this dumbass dll file that makes u move in a monkey game

**Comment by GiraffeasGorilla** [comment]
> man freak it I'm doing this for you freak your friend that told you to stop updating it I'm gonna remake it trust me if I go to jail I do not care and I'm 14 IM DOING THIS FOR YOU

first he is not my friend, second... just please dont do it man.

**Comment by Tavrie** [comment]
> > man freak it I'm doing this for you freak your friend that told you to stop updating it I'm gonna remake it trust me if I go to jail I do not care and I'm 14 IM DOING THIS FOR YOU
> 
> first he is not my friend, second... just please dont do it man.

really? who is it then?
